# Set the build language to Python
language: python

# Set the python version to 3.7
python:
- '3.7'

# Install dependencies
install:
- python -m pip install pytest requests
- python -m pip install -r requirements.txt

# Run tests
script:
- python -m pytest tests/test_package_tracking.py -v

# Install the codecov pip dependency
install:
- pip install codecov

# Run the unit test
script:
- coverage run tests/test_package_tracking.py

# Push the results back to codecov
after_success:
- codecov --token=ac82f897-9b59-421b-a090-aec30275be70
