# Set the build language to Python
language: python

# Set the python version to 3.6
python:
- '3.6'

# Install dependencies
install:
- python -m pip install pytest requests

# Run tests
script:
- python -m pytest tests/test_package_tracking.py -v
